### PR TITLE
Remove charts from repo

### PR DESCRIPTION
**Pull request by evrardjp**
As we'll be extracting charts to the new repository, there is no need to keep the current helm charts in this repository.

This allows us to have a cleaner code.

### CODE REVIEW

**Review by dholbach — APPROVED** [review]
Thanks @evrardjp

**Comment by dan-leanix** [comment]
@dholbach @evrardjp Might it be that this change breaks Helm chart deployments? We received today on our Terraform runs the following error:

```
Error: looks like "https://weaveworks.github.io/kured" is not a valid chart repository or cannot be reached: failed to fetch https://weaveworks.github.io/kured/index.yaml : 404 Not Found
```

**Comment by dholbach** [comment]
@dan-leanix Can you update to `kubereboot.github.io/charts` and make sure you have 4.0.1?

**Comment by dan-leanix** [comment]
@dholbach https://github.com/kubereboot/kured/issues/654 I am on it. Looking at https://kubereboot.github.io/charts/index.yaml and the URLs `3.0.0` should still work.

**Comment by dan-leanix** [comment]
@dholbach `kubereboot.github.io/charts` fixed the issue for us. Thanks again for the quick response.

**Pull request merged**
