### PR TITLE
Make metrics port configurable

### PR DESCRIPTION
**Pull request by adityasundaramurthy-maersk**
Resolves https://github.com/kubereboot/kured/issues/696

### CODE REVIEW

**Comment by jackfrancis** [comment]
@adityasundaramurthy-maersk can you address the error in the DCO job? Thanks!

**Review by ckotzbauer — COMMENTED** [review]
Thanks for the PR. Can you please mention this option shortly in the README?

**Comment by adityasundaramurthy-maersk** [comment]
Sorry for the messy commit log. I simply couldn't get the DCO signed off. Hope you can squash those commits.

**Comment by jackfrancis** [comment]
@adityasundaramurthy-maersk I think we only want the updates to `main.go` and `README.md`, we don't want to update any library dependencies as a part of this change

**Comment by ckotzbauer** [comment]
@adityasundaramurthy-maersk Any news on this?

**Pull request closed without merging**
