### PR TITLE
Change organisation to kubereboot, drop Docker Hub build

### PR DESCRIPTION
**Pull request by dholbach**
Also drop Docker Hub as discussed.

Areas I did not touch:
- bot name, secrets
- image name
- LICENSE (would need to ask how/if that gets changed...?)
- anything in charts/ - will be handled by separate PR
- one mention in the Dev docs that we used to do some pre-release smoke-testing on the Weave Dev cluster

Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by evrardjp** [comment]
We also need to change the actions, and maybe put all of those inside a merge_queue.

**Comment by dholbach** [comment]
Feel free to add to this branch.

**Comment by evrardjp** [comment]
If you rebase, this should pass tests.

**Comment by dholbach** [comment]
It's rebased to latest `main`. Unfortunately the e2e tests are not quite happy yet.

**Review by evrardjp — APPROVED** [review]
Let's try this and see.

**Pull request merged**
